---

github:
  branch_develop: develop
  branch_master: master
  owner: aussielunix
  repo: belvedere
  uri: https://github.com/aussielunix/belvedere.git

cf:
  api: https://api.run.pivotal.io
  skip_ssl_check: false
  username: ((pws_creds.username))
  password: ((pws_creds.password))
  develop:
    org: aussielunix
    space: development
    appname: belvedere-dev
  master:
    org: aussielunix
    space: staging
    appname: belvedere-staging

docker:
  image: aussielunix/mkdocs