---

jobs:
- name: website-develop
  plan:
  - get: git-develop
    trigger: true
  - task: build-site
    config:
      platform: linux
      inputs:
      - name: git-develop
      outputs:
      - name: site
      image_resource:
        type: docker-image
        source:
          repository: ((docker.image))
          tag: latest
      run:
        path: mkdocs
        args: ["build"]
  public: false
  
- name: website-master
  plan:
  - get: git-master
    trigger: true
  - task: build-site
    config:
      platform: linux
      inputs:
      - name: git-master
      outputs:
      - name: site
      image_resource:
        type: docker-image
        source:
          repository: ((docker.image))
          tag: latest
      run:
        path: mkdocs
        args: ["build"]
  - task: list-site-content
    config:
      platform: linux
      inputs:
      - name: git-master
      image_resource:
        type: docker-image
        source: { repository: alpine }
      run:
        path: sh
        args:
        - -exc
        - |
          ls -R ./git-master:w

resources:
- name: git-develop
  type: git
  source:
    branch: ((github.branch_develop))
    uri: ((github.uri))

- name: git-master
  type: git
  source:
    branch: ((github.branch_master))
    uri: ((github.uri))
    
#- name: deploy-develop
#  source:
#    api: ((cf.api))
#    organization: ((cf.develop.org))
#    password: ((cf.password))
#    skip_cert_check: ((cf.skip_ssl_check))
#    space: ((cf.develop.space))
#    username: ((cf.username))
#  type: cf
    #- name: deploy-master
    #  source:
    #    api: ((cf.api))
    #    organization: ((cf.master.org))
    #    password: ((cf.password))
    #    skip_cert_check: ((cf.skip_ssl_check))
    #    space: ((cf.master.space))
    #    username: ((cf.username))
    #  type: cf
